language: go

sudo: false

go:
    - master

before_install:
    - go get github.com/mattn/goveralls
    - go get github.com/voidint/gbb

script:
    - GOOS=darwin gbb --debug
    - GOOS=windows gbb --debug
    - GOOS=linux gbb --debug
    - $HOME/gopath/bin/goveralls -service=travis-ci
    