swagger: '2.0'
info:
  version: v2
  title: 通用配置管理
  description: 通用配置管理
host: dcoscfg.stable.idcos.net:8012
schemes:
  - http
# will be prefixed to all paths
basePath: /api/v2
consumes:
  - application/json
produces:
  - application/json
paths:
  /common-configuration:
    post:
      summary: 创建通用配置
      description: 创建一个通用配置，并将其保存到 CMDB
      parameters:
        - name: jsonInBody
          description: HTTP Body中的json格式的数据。
          required: true
          in: body
          schema:
            type: object
            properties:
              name:
                description: 通用配置项名称
                type: string
              cmConfJson:
                description: 通用配置JSON结构(内容不固定)
                type: object
          
      responses:
        200:
          description: 通用配置创建结果
          schema:
            $ref: '#/definitions/ChangeCommonConfigResp'
          
    put:
      summary: 更新通用配置
      description: 更新一个通用配置，并将更新结果其保存到 CMDB
      parameters:
        - name: jsonInBody
          description: HTTP Body中的json格式的数据。
          required: true
          in: body
          schema:
            type: object
            properties:
              id:
                description: 通用配置ID
                type: string
              name:
                description: 通用配置项名称
                type: string
              cmConfJson:
                description: 通用配置JSON结构(内容不固定)
                type: object
          
      responses:
        200:
          description: 通用配置更新结果
          schema:
            $ref: '#/definitions/ChangeCommonConfigResp'
          
    get:
      summary: 查询通用配置分页列表
      description: 查询通用配置分页列表
      parameters:
        - name: page
          description: 当前分页页号(自`1`始)
          required: false
          type: integer
          in: query
          default: 1
          minimum: 1
          
          
        - name: count
          description: 分页大小(条目数)
          required: false
          type: integer
          in: query
          default: 20
          minimum: 1
          maximum: 100
          
        - name: name
          description: 通用配置名称(可模糊查询)
          required: false
          type: string
          in: query
          
      responses:
        200:
          description: 获取通用配置
          schema:
            $ref: '#/definitions/GetCommonConfigPageResp'
        
        
  /common-configuration/{id}:    
    get:
      summary: 获取通用配置
      description: 分页获取通用配置
      parameters:
        - name: id
          type: string
          required: true
          in: path
          
      responses:
        200:
          description: 获取通用配置
          schema:
            $ref: '#/definitions/GetCommonConfigResp'
            
    delete:
      summary: 删除一个通用配置
      description: 根据ID删除通用配置
      parameters:
        - name: id
          type: string
          required: true
          in: path
          
      responses:
        200:
          description: 删除通用配置结果
          schema:
            $ref: '#/definitions/ChangeCommonConfigResp'
    
            
            
            
definitions:
  ChangeCommonConfigResp:
    type: object
    properties: 
      status:
        type: string
      message:
        type: string
      content:
        type: object
        properties:
          id:
            type: string
            description: 通用配置ID
            
            
  GetCommonConfigPageResp:
    type: object
    properties: 
      status:
        type: string
        description: 状态值
        enum: ["success", "error"]
      message:
        type: string
        description: 响应描述
      content:
        type: object
        description: 响应具体内容对象
        properties:
          page:
            type: integer
            description: 分页页号
          count:
            type: integer
            description: 分页大小
          total:
            type: integer
            description: 总记录数
          results:
            type: array
            description: 通过配置分页列表
            items:
              type: object
              properties:
                id:
                  type: string
                  description: 通用配置ID
                name:
                  type: string
                  description: 通用配置名称
                cmConfJson:
                  description: 通用配置JSON结构(内容不固定)
                  type: object
            
                
                  
                  
            
  GetCommonConfigResp:
    type: object
    properties: 
      status:
        type: string
        description: 状态值
        enum: ["success", "error"]
      message:
        type: string
        description: 响应描述
      content:
        type: object
        description: 响应具体内容对象
        properties:
          id:
            type: string
            description: 通用配置ID
          name:
            type: string
            description: 通用配置名称
          cmConfJson:
            description: 通用配置JSON结构(内容不固定)
            type: object
          
            
