swagger: '2.0'
info:
  version: v2
  title: 批量命令执行工具
  description: 批量命令执行工具
host: dcoscfg.stable.idcos.net:8012
schemes:
  - http
basePath: /api/cli/v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /task/exec:
    post:
      summary: 对一台或者多台主机异步地执行指定的命令
      description: |
        使用指定的执行插件，在一台或者多台主机上异步地执行指定的命令。
      parameters:
        - name: jsonInBody
          in: body
          schema:
            type: object
            properties:
              cmd:
                description: 待执行的命令
                type: string
                required: true
              timeout:
                description: 命令执行超时时间
                type: integer
                required: true
                minimum: 1
              pluginType:
                description: 执行命令所使用的插件
                type: string
                required: true
                enum: ["MCO", "MCOSimple", "SSH"]
              userNodes:
                description: 执行用户与目标主机名信息对
                required: true
                type: array
                items:
                  type: object
                  properties:
                    userName:
                      description: 执行命令所使用的用户帐号名称
                      type: string
                      required: true
                    nodeName:
                      description: 目标主机名称
                      type: string
                      required: true
                
                
                
      responses:
        200:
          description: 返回命令执行任务ID列表。
          schema:
            $ref: '#/definitions/ExecResp'
          
    

  /task/view:
    post:
      summary: 根据命令执行任务ID列表查询执行结果
      description: |
        若指定ID的任务未完成，则该执行结果不包含在响应的结果中，此种情况下，更合理的方式就是对未返回结果的命令执行继续*轮询*接口，直至超时（调用方自身设定的超时时间）或者命令执行结果全部完成为止。
      parameters:
        - name: jsonInBody
          in: body
          schema:
            type: object
            properties:
              taskIDs:
                description: 未完成命令执行的任务ID列表
                type: array
                items:
                  type: string
                  uniqueItems: true
          description: HTTP Body中的json格式的数据。
          required: true
      responses:
        200:
          description: 返回命令执行任务ID列表。
          schema:
            $ref: '#/definitions/ViewExecResultsResp'
          

definitions:
  ExecResp:
    description: 执行命令响应对象
    type: object
    properties: 
      status:
        type: string
        description: 状态值
        enum: ["success", "error"]
      message:
        type: string
        description: 响应描述
      content:
        type: object
        description: 响应具体内容对象
        properties:
          taskIDs:
            type: array
            description: 命令执行任务ID列表
            items:
              type: string
  ViewExecResultsResp:
    description: 查询命令执行结果响应对象
    type: object
    properties: 
      status:
        type: string
        description: 状态值
        enum: ["success", "error"]
      message:
        type: string
        description: 响应描述
      content:
        type: object
        description: 响应具体内容对象
        properties:
          results:
            type: array
            items:
              type: object
              properties:
                taskID:
                  type: string
                  description: 命令执行任务ID
                nodeName:
                  type: string
                  description: 命令执行目标主机名
                stdout:
                  type: string
                  description: 命令执行标准输出（当且仅当`exitCode==0`时具有参考意义）
                stderr:
                  type: string
                  description: 命令执行标准错误输出（当且仅当`exitCode!=0`时具有参考意义）
                status:
                  type: string
                  description: | 
                    命令执行结果状态值。
                    - `DONE`表示命令已经在目标主机上执行完毕。
                    - `ERRORED`表示命令执行任务在调度过程中发生错误，命令还未开始在目标主机上执行。
                    - `FIND_HOST_TIMEOUT`表示查找目标主机超时。
                    - `HOST_EXEC_TIMEOUT`表示命令已经在目标主机上开始执行，但是未在超时时间内执行完毕。
                statusInfo:
                  type: string
                  description: 命令执行结果状态值描述
                exitCode:
                  type: integer
                  format: int32
                  description: | 
                    命令执行退出码。
                    - 当`status==DONE`并且`exitCode==0`时，表示命令在目标主机上被执行并且退出码为`0`。
                    - 当`status==DONE`并且`exitCode!=0`时，表示命令在目标主机上被执行并且退出码不为`0`。
                    - 当`status!=DONE`时，`exitCode`不具有参考意义。
                begin:
                  type: long
                  format: int64
                  description: 目标主机开始命令执行的[UNIX时间戳](http://baike.baidu.com/view/821460.htm)
                end:
                  type: long
                  format: int64
                  description: 目标主机结束命令执行的[UNIX时间戳](http://baike.baidu.com/view/821460.htm)
                
                  
                
              
            
        
